### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [datdot-ui/datdot-ui#1]
## `@todo`

* [ ] #2 
* [ ] create project github issue structure and figma file
  * `@input` :question: `final datdot project task and subtask issues structure` from #2
  * [ ] refine github issue structure with everything missing from the old datdotorg/datdot-ui repo issues
  * [ ] rename existing datdot-ui repositories based on proposed component structure
  * [ ] create missing datdot-ui repositories for planned components
  * [ ] create issues based on final datdot project task and subtask issues structure
  * [ ] create datdot figma version controlled wireframes for datdot ux/ui with pages for each component
  * `@output` :question: `initial datdot figma versioned wireframes`
    * next #3
    * next #4
* [ ] #3
* [ ] #4
* [ ] #5
* [ ] #6

**Comment by Mehrabbruno** [comment]
# tasks

- study datdot project videos 
   - datdot intro script - `14min`
   - datdot intro video - `10min` 
   - datdot-ui overview video - `9min`
   - datdot-ui component implementations video - `11min`
   - datdot-ui-wireframes video - `12min`

 - study datdot.org website and datdot.org wireframes
    - propose a versioned web component structure for wireframes - `3h8min`
       - `@output` 📦 [`tasks_for_datdot.or`](https://hackmd.io/@bmEyR385TzK1cdDl54ixTw/rkYRjj58o)
    - create task and subtask for current repos - `1h56min`
       - `@output` 📦 [`tasks_for_current_component_repo`](https://hackmd.io/@bmEyR385TzK1cdDl54ixTw/B1sdSwKUo)

---

# feedback

I created two hackmd containing list of tasks. 1 for the repos on the github org and other one for the wireframe of the datdot.org. 
another document is in progress where I am listing all the components for the apps.

All the components are mostly taken from the Adobe XD files. I couldn't seem to download any wallet or test it any way except for the adobe xd. So, I am using those files as a reference for now.

---

# worklog

---

#proposal

**Comment by Mehrabbruno** [comment]
All the worklogs are moved to 
#2
