### ISSUE TITLE
wireframe datdot-org components

### ISSUE THREAD

**Issue by serapath** [datdot-ui/datdot-ui#3]
## `@todo`
* [ ] translate `datdot.org wireframes` as is with no UI changes into `datdot figma versioned wireframes`
   * [ ] add all existing component wireframe versions
      * `@input` :question: `initial datdot figma versioned wireframes` from #1
      * `@output` :question: `datdot-org figma versioned wireframes`
   * [ ] add additional missing component design versions to `datdot figma versioned wireframes` document
      * `@input` :question: `datdot-org figma versioned wireframes`
      * `@output` :question: `refined datdot-org figma versioned wireframes`
        * next #5
