### ISSUE TITLE
wireframe datdot-app components

### ISSUE THREAD

**Issue by serapath** [datdot-ui/datdot-ui#4]
## `@todo`
* [ ] translate `datdot-ui wireframes` as is with no UI changes into `datdot figma versioned wireframes`
   * [ ] add all existing component wireframe versions
      * `@input` :question: `initial datdot figma versioned wireframes` from #1
      * `@output` :question: `datdot-ui figma versioned wireframes`
   * [ ] add additional missing component design versions to `datdot figma versioned wireframes` document
      * `@input` :question: `datdot-ui figma versioned wireframes`
      * `@output` :question: `refined datdot-ui figma versioned wireframes`
        * next #5
