### ISSUE TITLE
improve all wireframed components

### ISSUE THREAD

**Issue by serapath** [datdot-ui/datdot-ui#5]
## `@todo`
* [ ] improve all wireframed components by adding new iteration versions to existing components
   * `@input` :question: `refined datdot-ui figma versioned wireframes` from #3
   * `@input` :question: `refined datdot-org figma versioned wireframes` from #4
   * [ ] discuss datdot-ui to create concept for datdot-ui update
   * [ ] propose task structure hackmd document per component with all update plans
     * `@output` :question: `component designs refinement plan`
  * [ ] add all relevant tasks to each components issue and work on next component design versions
     * `@input` :question: `component designs refinement plan`
     * [ ] design versions
     * `@output` :question: `final datdot figma versioned wireframes`
       * next #6
