### ISSUE TITLE
implement datdot components

### ISSUE THREAD

**Issue by serapath** [datdot-ui/datdot-ui#6]
## `@todo`
* [ ] implement datot components
   * `@input` :question: `final datdot figma versioned wireframes` from #5
   * [ ] updating existing basic components in vanillajs
     * `@output` :question: `updated existing component repositories with latest commit`
       * next :checkered_flag: 
   * [ ] implement all missing components in vanillajs
     * `@output` :question: `new component repositories with latest commit`
       * next :checkered_flag:
